### PR TITLE
Fix ddslick select index 0 not working

### PR DESCRIPTION
**Pull request by datphan**

### CODE REVIEW

**Comment by hoatle** [comment]
to include this fix: https://github.com/prashantchaudhary/ddslick/pull/16/files

**Comment by hoatle** [comment]
@Maluen including minified versions is very hard to work with.

**Comment by Maluen** [comment]
@hoatle we can include the un-minified version, the minification is done on iorad via grunt.

**Comment by hoatle** [comment]
@Maluen ok, I'll check all the libs and use source instead of min files if any.

**Pull request merged**
